AWS_UPLOAD_BUCKET = "internbuck"

AWS_UPLOAD_USERNAME = "CFE_user_justin"

AWS_UPLOAD_GROUP = "CFE_AwesomeGroup"

AWS_UPLOAD_REGION = 'us-west-2'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIAIVHWXORRJYYJK6LA"

AWS_UPLOAD_SECRET_KEY = "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"
